package io.jpyxis.resilience.evidence;

public enum EventOwner {
    WORKER_SUPERVISOR,
    WORKER_CAPABILITY,
    RESILIENT_INVOCATION_MANAGER,
    ATTEMPT_CAPABILITY,
    CONTROL_INTENT_REGISTRY,
    RECOVERY_COORDINATOR,
    OBSERVABILITY_COORDINATOR
}
